library(usethis)

locate_test <- 
  tibble::tribble(
             ~.value, ~.direction, ~.header_label, ~address, ~row, ~col,  ~data_type,    ~character, ~numeric, ~date, ~logical, ~error, ~is_blank, ~local_format_id,              ~sheet,                                                                                                                                                                                                        ~character_formatted, ~formula, ~is_array, ~formula_ref, ~formula_group, ~comment, ~height,    ~width, ~style_format, ~dc,
            "Female",       "NNW",       "gender",     "D2",   2L,   4L, "character",      "Female",       NA,    NA,       NA,     NA,     FALSE,              18L, "pivot-annotations",      list(character = "Female", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
                  NA,          NA,             NA,     "E2",   2L,   5L,     "blank",            NA,       NA,    NA,       NA,     NA,      TRUE,              19L, "pivot-annotations",                                                                                                                                                                                                                        NULL,       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
              "Male",       "NNW",       "gender",     "F2",   2L,   6L, "character",        "Male",       NA,    NA,       NA,     NA,     FALSE,              18L, "pivot-annotations",        list(character = "Male", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
                  NA,          NA,             NA,     "G2",   2L,   7L,     "blank",            NA,       NA,    NA,       NA,     NA,      TRUE,              19L, "pivot-annotations",                                                                                                                                                                                                                        NULL,       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
           "Matilda",         "N",         "name",     "D3",   3L,   4L, "character",     "Matilda",       NA,    NA,       NA,     NA,     FALSE,              20L, "pivot-annotations",     list(character = "Matilda", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
            "Olivia",         "N",         "name",     "E3",   3L,   5L, "character",      "Olivia",       NA,    NA,       NA,     NA,     FALSE,              21L, "pivot-annotations",      list(character = "Olivia", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
          "Nicholas",         "N",         "name",     "F3",   3L,   6L, "character",    "Nicholas",       NA,    NA,       NA,     NA,     FALSE,              20L, "pivot-annotations",    list(character = "Nicholas", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
              "Paul",         "N",         "name",     "G3",   3L,   7L, "character",        "Paul",       NA,    NA,       NA,     NA,     FALSE,              21L, "pivot-annotations",        list(character = "Paul", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
        "Humanities",       "WNW", "subject_type",     "B4",   4L,   2L, "character",  "Humanities",       NA,    NA,       NA,     NA,     FALSE,              18L, "pivot-annotations",  list(character = "Humanities", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
          "Classics",         "W",      "subject",     "C4",   4L,   3L, "character",    "Classics",       NA,    NA,       NA,     NA,     FALSE,              19L, "pivot-annotations",    list(character = "Classics", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
                  NA,          NA,             NA,     "B5",   5L,   2L,     "blank",            NA,       NA,    NA,       NA,     NA,      TRUE,              20L, "pivot-annotations",                                                                                                                                                                                                                        NULL,       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
           "History",         "W",      "subject",     "C5",   5L,   3L, "character",     "History",       NA,    NA,       NA,     NA,     FALSE,              21L, "pivot-annotations",     list(character = "History", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
       "Performance",       "WNW", "subject_type",     "B6",   6L,   2L, "character", "Performance",       NA,    NA,       NA,     NA,     FALSE,              20L, "pivot-annotations", list(character = "Performance", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
             "Music",         "W",      "subject",     "C6",   6L,   3L, "character",       "Music",       NA,    NA,       NA,     NA,     FALSE,              21L, "pivot-annotations",       list(character = "Music", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
                  NA,          NA,             NA,     "B7",   7L,   2L,     "blank",            NA,       NA,    NA,       NA,     NA,      TRUE,              24L, "pivot-annotations",                                                                                                                                                                                                                        NULL,       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA,
             "Drama",         "W",      "subject",     "C7",   7L,   3L, "character",       "Drama",       NA,    NA,       NA,     NA,     FALSE,              25L, "pivot-annotations",       list(character = "Drama", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 8.7109375,      "Normal",  NA
       )
  

  usethis::use_data(locate_test,overwrite = TRUE)