library(usethis)

locate_groups_test<- 
  tibble::tribble(
             ~.value, ~.direction,      ~.header_label, ~address, ~row, ~col,  ~data_type,    ~character, ~numeric, ~date, ~logical, ~error, ~is_blank, ~local_format_id,            ~sheet,                                                                                                                                                                                                        ~character_formatted, ~formula, ~is_array, ~formula_ref, ~formula_group, ~comment, ~height,      ~width, ~style_format, ~fmt_alignment_indent, ~dc,
           "Matilda",         "N",           "student",     "C2",   2L,   3L, "character",     "Matilda",       NA,    NA,       NA,     NA,     FALSE,              18L, "pivot-hierarchy",     list(character = "Matilda", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15,           9,      "Normal",                    0L,  NA,
          "Nicholas",         "N",           "student",     "D2",   2L,   4L, "character",    "Nicholas",       NA,    NA,       NA,     NA,     FALSE,              42L, "pivot-hierarchy",    list(character = "Nicholas", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15,           9,      "Normal",                    0L,  NA,
        "Humanities",       "WNW", "W_header_label_01",     "B3",   3L,   2L, "character",  "Humanities",       NA,    NA,       NA,     NA,     FALSE,              18L, "pivot-hierarchy",  list(character = "Humanities", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 14.42578125,      "Normal",                    0L,  NA,
                  NA,          NA,                  NA,     "C3",   3L,   3L,     "blank",            NA,       NA,    NA,       NA,     NA,      TRUE,              18L, "pivot-hierarchy",                                                                                                                                                                                                                        NULL,       NA,     FALSE,           NA,             NA,       NA,      15,           9,      "Normal",                    0L,  NA,
                  NA,          NA,                  NA,     "D3",   3L,   4L,     "blank",            NA,       NA,    NA,       NA,     NA,      TRUE,              43L, "pivot-hierarchy",                                                                                                                                                                                                                        NULL,       NA,     FALSE,           NA,             NA,       NA,      15,           9,      "Normal",                    0L,  NA,
          "Classics",         "W", "W_header_label_02",     "B4",   4L,   2L, "character",    "Classics",       NA,    NA,       NA,     NA,     FALSE,              44L, "pivot-hierarchy",    list(character = "Classics", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 14.42578125,      "Normal",                    1L,  NA,
           "History",         "W", "W_header_label_02",     "B5",   5L,   2L, "character",     "History",       NA,    NA,       NA,     NA,     FALSE,              44L, "pivot-hierarchy",     list(character = "History", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 14.42578125,      "Normal",                    1L,  NA,
       "Performance",       "WNW", "W_header_label_01",     "B6",   6L,   2L, "character", "Performance",       NA,    NA,       NA,     NA,     FALSE,              20L, "pivot-hierarchy", list(character = "Performance", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 14.42578125,      "Normal",                    0L,  NA,
                  NA,          NA,                  NA,     "C6",   6L,   3L,     "blank",            NA,       NA,    NA,       NA,     NA,      TRUE,              20L, "pivot-hierarchy",                                                                                                                                                                                                                        NULL,       NA,     FALSE,           NA,             NA,       NA,      15,           9,      "Normal",                    0L,  NA,
                  NA,          NA,                  NA,     "D6",   6L,   4L,     "blank",            NA,       NA,    NA,       NA,     NA,      TRUE,              45L, "pivot-hierarchy",                                                                                                                                                                                                                        NULL,       NA,     FALSE,           NA,             NA,       NA,      15,           9,      "Normal",                    0L,  NA,
             "Music",         "W", "W_header_label_02",     "B7",   7L,   2L, "character",       "Music",       NA,    NA,       NA,     NA,     FALSE,              44L, "pivot-hierarchy",       list(character = "Music", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 14.42578125,      "Normal",                    1L,  NA,
             "Drama",         "W", "W_header_label_02",     "B8",   8L,   2L, "character",       "Drama",       NA,    NA,       NA,     NA,     FALSE,              46L, "pivot-hierarchy",       list(character = "Drama", bold = NA, italic = NA, underline = NA, strike = NA, vertAlign = NA, size = NA, color_rgb = NA, color_theme = NA, color_indexed = NA, color_tint = NA, font = NA, family = NA, scheme = NA),       NA,     FALSE,           NA,             NA,       NA,      15, 14.42578125,      "Normal",                    1L,  NA
       )

usethis::use_data(locate_groups_test,overwrite = TRUE)