---
title: "Examples"
author: "Ian Moran"
date: "28/04/2019"
output:   
  html_document
editor_options: 
  chunk_output_type: console
---


```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tibble.print_min = 100, tibble.print_max = 100)
options(width=100)
```

```{r}
rm(list = ls())
setwd("C:/Users/Ian/Data/r-projects/unpivotr-dev/unpivotr/vignettes")
home_dir <- rprojroot::find_package_root_file()
setwd(home_dir)
```




#### Setup packages 
```{r message=FALSE, warning=FALSE, include=FALSE}
library(devtools)
install_github("nacnudus/unpivotr",ref = "ian")
library(unpivotr)
library(rprojroot)
library(magick)
library(magrittr)
library(tidyverse)
library(tidyxl)
library(stringr)
library(rlang)
library(lubridate)
library(hrbrthemes)
library(scales)
```

#### Load in newresconst.xlsx
```{r message=FALSE, warning=FALSE}



workbook_path <- unpivotr_example("newresconst.xlsx")
sheet_name <- "Table 1 - Permits"

testsheet_df <- xlsx_cells(path = workbook_path, sheets = sheet_name)
formats <- xlsx_formats(workbook_path)

table_min_row <- 
  testsheet_df$character %>% 
    str_detect("Average RSE") %>% 
    which() %>% min() %>% 
    testsheet_df$row[.] 

orientated_df <-  
  orientate_auto(table_range = ~ row < table_min_row,
                 sheet = testsheet_df,formats = formats,
                 manual_value_references = ~ data_type == "numeric" &  col >1,
                 group_row_headers_by = list(fmt_alignment_indent, ~data_type),
                 col_header_fill = "style")

orientated_df_auto %>% plot_orientations()

new_housing_df <-
  orientated_df_auto %>% 
  migrate(numeric_value = T)

new_housing_df <- 
  new_housing_df %>% set_names(c("row","col",".value","region","units","year_var","month_var")) %>% 
    mutate(month_var = month_var %>% str_remove_all("\\.") %>% str_trim())  %>% 
    mutate(date_var = ymd(paste(year_var,month_var,"15",sep = "-")))

new_housing_df %>% 
    ggplot(aes(x = date_var , y = .value, color =units )) + 
    geom_line() + facet_grid(region~.,scales = "free") + theme_bw() +
    labs(color = "Number of units", x = "Date", y ="New Privately-Owned Housing Units Authorized in Permit-Issuing Places ('000s)" )

```


```{r}

workbook_path <- unpivotr_example("newresconst.xlsx")
sheet_name <- "Table 1 - Permits"

get_table <-  function(sheet_name){
  
testsheet_df <- xlsx_cells(path = workbook_path, sheets = sheet_name)
formats <- xlsx_formats(workbook_path)

table_min_row <-  testsheet_df$character %>% str_detect("Average RSE") %>% 
                  which() %>% min() %>% testsheet_df$row[.] 

migrated_df <-  
  orientate_auto(
    table_range = ~ row < table_min_row, sheet = testsheet_df,formats = formats,
    manual_value_references = ~ data_type == "numeric" &  col >1,
    group_row_headers_by = list(fmt_alignment_indent, ~data_type),
    col_header_fill = "style")%>% 
  migrate(numeric_value = T)

  migrated_df %>% set_names(c("row","col",".value","region","units","year_var","month_var")) %>% 
    mutate(month_var = month_var %>% str_remove_all("\\.") %>% str_trim())  %>% 
    mutate(date_var = ymd(paste(year_var,month_var,"15",sep = "-")))

}

sheets <- tidyxl::xlsx_sheet_names(workbook_path)

housing_df <- sheets %>% map_dfr(get_table)



new_housing_df %>% 
    ggplot(aes(x = date_var , y = .value, color =units )) + 
    geom_line() + facet_grid(region~.,scales = "free") + theme_bw() +
    labs(color = "Number of units", x = "Date", y ="New Privately-Owned Housing Units Authorized in Permit-Issuing Places ('000s)" )



```





```{r}

orientated_df_aut <-  
  orientate_auto(
                range = ~row < min(anchor_rows)
                sheet = testsheet_df,formats = formats,
                manual_value_references = ~ data_type == "numeric" & 
                                            col >1 & row < max(anchor_rows) & row > max(top_rows),
                group_row_headers_by = list(fmt_alignment_indent, ~data_type),
                filter_col_headers_by = ~ row > max(top_rows) & col ==1,
                filter_row_headers_by = ~ row > max(anchor_rows)& row < max(anchor_rows),
                col_header_fill = "style")

orientated_df_auto_sa %>% plot_orientations()

orientated_df_auto %>% migrate(numeric_value = T)

orientated_df_auto <-  orientate_auto(sheet = testsheet_df,formats = formats,
                                      manual_value_references = ~ data_type == "numeric" & 
                                                                  fmt_font_italic(local_format_id,formats) == "TRUE" & 
                                                                  row < 31 & row > 25,
                                      group_row_headers_by = list(fmt_alignment_indent, ~data_type),
                                      group_col_headers_by = list(~ row < 6),
                                      filter_col_headers_by = ~row <7 & col > 1,
                                      filter_row_headers_by = ~row > 25 & row < 31 & col == 1,
                                      col_header_fill = "style")

orientated_df_auto %>% plot_orientations()
orientated_df_auto %>% migrate() %>% View

testsheet_df

new_housing_df %>% View
new_housing_df <- 
  orientated_df_auto %>% migrate(numeric_value = T)  

# Clean data 
(new_housing_df <- 
  new_housing_df %>% set_names(c("row","col",".value","region","units","year_var","month_var")) %>% 
    mutate(month_var = month_var %>% str_remove_all("\\.") %>% str_trim())  %>% 
    mutate(date_var = ymd(paste(year_var,month_var,"15",sep = "-"))) %>% 
    group_by(region, units) %>% 
    mutate(.value = 100*(.value / first(.value,order_by = date_var))))
  

new_housing_df %>% 
    ggplot(aes(x = date_var , y = .value, color =units )) + 
    geom_line() + facet_grid(region~.) + theme_bw() +
    labs(color = "Number of units", x = "Date", y ="New Privately-Owned Housing Units Authorized in Permit-Issuing Places ('000s)" )


```


```{r}
tidyxl::xlsx_sheet_names(workbook_path)

```


