---
  title: "Tidying with unpivotr locate functions"
output:   
  html_document:
  keep_html: true
editor_options: 
  chunk_output_type: console
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
# Load all packages 
install.packages("pacman");
library("pacman")
(p_load(here,stringr,purrr,dplyr,rlang,magrittr,ggplot2,cowplot,plotly,
        unpivotr, magick, magrittr, tidyverse, stringr, rlang, lubridate,
        hrbrthemes, scales, devtools,rlang))
devtools::install_github(repo = "ianmoran11/tidyxl")
library(tidyxl)

devtools::install_github(repo = "nacnudus/unpivotr", ref = "ian")
library(unpivotr)
```


```{r message=FALSE, warning=FALSE, include=FALSE}





"workbook.xlsx" %>% 
  xlsx_cells_fmt(sheets = "Sheet1") %>% 
  locate_data(data_type == "numeric") %>% 
  locate("WNW",subject_type) %>% 
  locate("W",subject) %>% 
  locate("NNW",gender) %>%
  locate("N",name) %>%
  migrate()


































```



```{r}

unpivotr_example("newresconst.xlsx") %>% 
  xlsx_cells_fmt(sheets = "Table 1 - Permits") %>%
  filter_fmt(row < min(row[str_detect(character,"RSE")],na.rm = TRUE)) %>% 
  locate_data(data_type == "numeric" & col > 1) %>%
  locate_groups(type = "row", .groupings = groupings(is.na(numeric))) %>% 
  locate_groups(type = "col", header_fill = "style") %>%
  migrate()
  

   



```

