---
title: "New Functions Testing"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up 

```{r cars}
# Clear environment 
rm(list = ls())

install.packages("pacman");
library("pacman")
p_load(here,piton)

# Load all packages 
devtools::load_all(file.path(dirname(here::here()),"tidyxl"))
devtools::load_all(here::here())

# Install packages
p_load(stringr,purrr,dplyr,rlang,magrittr)
```


## 1.1 locate_data -> locate_groups ->  migrate 
```{r}
unpivotr_example("bball-examples.xlsx") %>%
  xlsx_cells_fmt(path = . , sheets = "Sheet1") %>% 
  locate_data(!is.na(numeric)) %>% 
  locate_header_groups_if(type = "col" , .groupings = groupings(fmt_font_bold,fmt_alignment_indent)) %>%
  locate_header_groups_if(type = "row" , .groupings = groupings(fmt_font_bold,fmt_alignment_indent)) %>%   
  migrate() 
```


## 1.1 locate_data -> locate_groups ->  migrate 
```{r}
unpivotr_example("bball-examples.xlsx") %>%
  xlsx_cells_fmt(path = . , sheets = "Sheet1") %>% 
  locate_data(!is.na(numeric)) %>% 
  locate_header_groups_if(row == 4, type = "col" , .groupings = groupings(fmt_font_bold,fmt_alignment_indent)) %>%
  locate_header_groups_if(type = "row" , .groupings = groupings(fmt_font_bold,fmt_alignment_indent)) %>%   
  migrate() 


unpivotr_example("bball-examples.xlsx") %>%
  xlsx_cells_fmt(path = . , sheets = "Sheet1") %>% 
  locate_header_groups_if(row == 4, type = "col" , .groupings = groupings(fmt_font_bold,fmt_alignment_indent)) %>%
  locate_header_groups_if(type = "row" , .groupings = groupings(fmt_font_bold,fmt_alignment_indent)) %>%   
  migrate() 



```







## 1.2                Locate_groups ->  migrate 
```{r}
unpivotr_example("bball-examples.xlsx") %>%
  xlsx_cells_fmt(path = . , sheets = "Sheet1") %>% 
  locate_header_groups(type = "col" , .groupings = groupings(fmt_font_bold,fmt_alignment_indent)) %>% 
  locate_header_groups(type = "row" , .groupings = groupings(fmt_font_bold,fmt_alignment_indent)) %>% 
  migrate() 
```

## 2.1 locate_data -> behead_groups ->  migrate 
```{r}
unpivotr_example("bball-examples.xlsx") %>%
  xlsx_cells_fmt(path = . , sheets = "Sheet1")  %>%
  locate_data(!is.na(numeric)) %>% 
  filter(row > 2) %>% 
  behead_dc("NNW","stat_type",types =data_type ) %>% 
  behead_dc("N","stat",types =data_type ) %>% 
  behead_dc("W","player",types =data_type ) %>% 
  attr("data_cells") %>% 
  select(row,col,contains("header"),stat_type,stat,player,contains("row"))
```

## 2.2             behead_groups ->  migrate 
```{r}
unpivotr_example("bball-examples.xlsx") %>%
  xlsx_cells_fmt(path = . , sheets = "Sheet1") %>% 
  behead_groups_if(type = "col" , .groupings = groupings(fmt_font_bold,fmt_alignment_indent)) %>% 
  behead_groups_if(type = "row" , .groupings = groupings(fmt_font_bold,fmt_alignment_indent)) %>% 
  attr("data_cells") %>% 
  select(row,col,contains("header"),contains("row"),.value) 
```


## 2.2             behead_groups ->  migrate 
```{r}

unpivotr_example("bball-examples.xlsx") %>%
  xlsx_cells_fmt(path = . , sheets = "Sheet1") %>% 
  behead_groups_if(row == 4, type = "col" , .groupings = groupings(fmt_font_bold,fmt_alignment_indent)) %>% 
  behead_groups_if(type = "row" , .groupings = groupings(fmt_font_bold,fmt_alignment_indent)) %>% 
  attr("data_cells") %>% 
  select(row,col,contains("header"),contains("row"),.value) 

```







## 3.1                       locate -> migrate 
```{r}
unpivotr_example("bball-examples.xlsx") %>%
  xlsx_cells_fmt(path = . , sheets = "Sheet1")  %>%
  filter(row > 2) %>% 
  locate_if(direction = "NNW",name = "stat_type",types =data_type ) %>%
  locate_if(direction = "N"  ,name = "stat"     ,types =data_type ) %>% 
  locate_if(direction = "W"  ,name = "player"   ,types =data_type ) %>% 
  mutate(.direction = ifelse(!is.na(numeric),"data",.direction)) %>% 
  mutate(.value = ifelse(.direction == "data", coalesce(as.character(numeric),as.character(character)),.value)) %>% 
 migrate_ndc()
```

## 3.2 locate_data -> locate -> migrate 
```{r}
unpivotr_example("bball-examples.xlsx") %>%
  xlsx_cells_fmt(path = . , sheets = "Sheet1") %>% 
  filter(row >2 ) %>%
  locate_data(!is.na(numeric)) %>% 
  locate_if(direction = "NNW",name = "stat_type",types =data_type ) %>%
  locate_if(direction = "N",name =  "stat",types =data_type ) %>%  
  locate_if(direction = "W",name = "player",types =data_type ) %>% 
  migrate() 
```

## 4.1              locate_if -> migrate 
```{r}
unpivotr_example("bball-examples.xlsx") %>%
  xlsx_cells_fmt(path = . , sheets = "Sheet1")  %>% 
  filter(row > 2) %>% 
  locate_if(col == 1 & !row %in% c(5,13) , direction = "W",name = "player",types = data_type ) %>% 
  locate_if(col == 1 & row %in% c(5,13) , direction = "WNW",name = "team",types = data_type ) %>% 
  locate_if(col > 1 & row ==4 ,           direction = "N",name = "stat"  ,types = data_type ) %>%  
  mutate(.direction = ifelse(!is.na(numeric),"data",.direction)) %>% 
  mutate(.value = ifelse(!is.na(numeric),numeric,.value)) %>% 
  migrate_ndc()
```


## 4.2  locate_data -> locate_if -> migrate 
```{r}
unpivotr_example("bball-examples.xlsx") %>%
  xlsx_cells_fmt(path = . , sheets = "Sheet1")  %>% 
  filter(row > 2) %>% 
  locate_data(!is.na(numeric)) %>%    
  locate_if(col == 1 & !row %in% c(5,13) , direction = "W",name = "player",types = data_type ) %>% 
  locate_if(col == 1 & row %in% c(5,13) , direction = "WNW",name = "team",types = data_type ) %>% 
  locate_if(col > 1 & row ==4 ,           direction = "N",name = "stat"  ,types = data_type ) %>% 
  migrate()
```


